word_hints = {0:{"adventure": "A quest for the unknown."}, 1:{"balloon": "Sky's the limit for this party favorite."},
    2:{"cabinet": "Storage with doors, not for clothes."}, 3:{"dolphin": "Intelligent oceanic acrobat."},
    4:{"elephant": "Giant with a trunk."}, 5:{"flamingo": "One-legged pink stand."},
    6:{"giraffe": "Skyscraper of the savannah."}, 7:{"harmony": "When different notes come together."},
    8:{"illusion": "More than meets the eye."}, 9:{"jewelry": "Worn for adornment, often shiny."},
    10:{"kangaroo": "Hopper with a pouch."}, 11:{"lantern": "Portable, often used when camping."},
    12:{"magnetic": "Attraction without the romance."}, 13:{"nebula": "Nursery of stars."},
    14:{"octagon": "More than just a shape for stop signs."}, 15:{"penguin": "A tuxedo in the Antarctic."},
    16:{"quartz": "Timekeeper's crystal."}, 17:{"rainbow": "A colorful arch after rain."},
    18:{"sapphire": "A gem that's blue."}, 19:{"treasure": "Pirates' coveted loot."},
    20:{"umbrella": "Protection from rain or shine."}, 21:{"victory": "Triumph's synonym."},
    22:{"waffle": "Breakfast with syrup traps."}, 23:{"xenon": "A noble gas with a cool glow."},
    24:{"yacht": "Luxury on water."}, 25:{"zeppelin": "Airship of the past."},
    26:{"acoustic": "Unplugged melody."}, 27:{"blizzard": "Snowstorm's fiercer cousin."},
    28:{"crystal": "Clear beauty, often fragile."}, 29:{"dynamite": "Explosive invention by Nobel."},
    30:{"eclipse": "Celestial shadow play."}, 31:{"festival": "Celebration en masse."},
    32:{"glacier": "Slow-moving ice river."}, 33:{"hurricane": "Spiraling tropical titan."},
    34:{"infinity": "Beyond count or measure."}, 35:{"jubilee": "A celebration of an anniversary."},
    36:{"knight": "Armored warrior of old."}, 37:{"landscape": "A vista of nature's artwork."},
    38:{"monarch": "A single ruler, often crowned."}, 39:{"nirvana": "Ultimate peace or enlightenment."}
}